#import <Streams/QueuingStrategyInit.idl>
#import <WebIDL/Function.idl>

// https://streams.spec.whatwg.org/#blqs-class-definition
[Exposed=*]
interface ByteLengthQueuingStrategy {
    constructor(QueuingStrategyInit init);

    readonly attribute unrestricted double highWaterMark;

    readonly attribute Function size;
};
